[package]
name = "pepeeltoro41/jecs-tween"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "node_modules",
    "src/index.d.ts",
    "package.json",
    "jecs.luau",
    "ripple.luau",
]

[dependencies]
ripple = "littensy/ripple@0.10.0-alpha.3"
jecs = "ukendio/jecs@0.9.0"
